# Generated by Django 5.1.7 on 2025-05-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="title",
            field=models.CharField(default="Untitled Report", max_length=200),
        ),
    ]
